on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # the name job
  name:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # echo name
    - name: PrintName
      run: echo "Ben Grummitt"

  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run setup
      run: bash setup.sh

  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node Modules
      working-directory: ./app
      run: npm install
    - name: Run Tests
      working-directory: ./app
      run: yarn run test
