on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # the setup job
  setup:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # echo name
    - name: PrintName
      run: echo "Ben Grummitt"

    - uses: actions/checkout@v2
    - name: Run setup
      run: bash setup.sh