on: [push, pull_request]

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - name: Print Benji's name
        run: echo "Benji :)"

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run setup
        run: bash setup.sh

  testapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        working-directory: ./app
        run: yarn install
      - name: Run tests
        working-directory: ./app
        run: yarn run test
