on: [push, pull_request]

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
    - name: Print stuff
      # you can have multiple lines using |
      run: |
        echo "yippee ki yay melonfarmer"
        echo "george oastler"
