on: [push, pull_request]

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
    - name: Print name
      run: echo "James"
  
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run setup
      run: bash setup.sh
      
      